alertmanager:

  tplConfig: true
  templateFiles:
     templates.tmpl: |-
        {{ define "cluster" }}{{ .ExternalURL | reReplaceAll ".*alertmanager\\.(.*)" "$1" }}{{ end }}
  
        {{ define "slack.myorg.text" }}
        {{- $root := . -}}
        {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
          *Cluster:* {{ template "cluster" $root }}
          *Description:* {{ .Annotations.description }}
          *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:>
          *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
          *Details:*
            {{ range .Labels.SortedPairs }} - *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
        {{ end }}
        {{ end }}

        {{ define "telegram.text" }}
        {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Labels:* 
            {{ range .Labels.SortedPairs }}
              {{ .Name }} "{{ .Value }}"
            {{ end }}
          *Details:*
            {{ range .Labels.SortedPairs }}
              {{ .Name }} "{{ .Value }}"
            {{ end }}
        {{ end }}
        {{ end }}

        {{ define "telegram.html" }}
        {{ range .Alerts }}
        <b>Alert:</b> {{ .Annotations.summary }}
        <b>Description:</b> {{ .Annotations.description }}
        <b>Labels:</b>
          {{ range .Labels.SortedPairs }}
            {{ .Name }} "{{ .Value }}"
          {{ end }}
        {{ end }}
        {{ end }}
