build:
  goarch:
    - amd64
    - arm
  env:
    - CGO_ENABLED=0
brew:
  github:
    owner: caarlos0
    name: homebrew-tap
  folder: Formula
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archive:
  name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
  files:
  - '_examples/*'
  - '*.md'
dockers:
  - image: caarlos0/domain_exporter
    tag_templates:
    - latest
    - "{{ .Tag }}"
    - "v{{ .Major }}"
