variables:
  description: Exports the expiration time of your domains in the Prometheus format.

includes:
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/build.yml
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/release.yml
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/package.yml
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/docker.yml
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/cosign_checksum.yml
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/cosign_docker.yml
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/sbom.yml

furies:
- account: caarlos0
