FROM golang as builder
WORKDIR /code
COPY go.mod go.sum /code/
RUN go mod download
COPY  . .
RUN go build -o /domain_exporter main.go

FROM gcr.io/distroless/base
EXPOSE 9222
WORKDIR /
COPY --from=builder /domain_exporter /usr/bin/domain_exporter
ENTRYPOINT ["/usr/bin/domain_exporter"]
