[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.5"

[[constraint]]
  branch = "master"
  name = "github.com/domainr/whois"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"
