apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-charts.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-charts.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ toYaml .Values.config | indent 4 }}
