{{- if .Values.alertmanagerconfig.enabled }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ template "helm-charts.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-charts.labels" . | nindent 4 }}
    release: kps
{{- with .Values.alertmanagerconfig.additionalLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- with .Values.alertmanagerconfig.route }}
  route:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.alertmanagerconfig.receivers }}
  receivers: 
{{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- end }}
