{{- if and (.Values.metrics.enabled) (.Values.metrics.podMonitor.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "helm-charts.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-charts.labels" . | nindent 4 }}
    release: kps
spec:
  podMetricsEndpoints:
  - targetPort: {{ .Values.service.port }}
  selector:
    matchLabels:
      {{- include "helm-charts.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    any: true
{{- end -}}
