apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-charts.fullname" . }}
  labels:
    {{- include "helm-charts.labels" . | nindent 4 }}
data:
  domains.yaml: |-
{{- if .Values.domains }}
    # User-supplied configuration:
{{ tpl .Values.domains . | indent 4 }}
{{- end }}
