% IANA WHOIS server
% for more information on IANA, visit http://www.iana.org
% This query returned 1 object

refer:        whois.ua

domain:       UA

organisation: Hostmaster Ltd.
address:      vul Vavilovykh 18
address:      Kyiv  04060
address:      Ukraine

contact:      administrative
name:         Dmitry Kohmanyuk
organisation: Hostmaster Ltd.
address:      P.O.Box 23
address:      Kyiv  04053
address:      Ukraine
phone:        +380 50 381 4604
e-mail:       dk@cctld.ua

contact:      technical
name:         Igor Sviridov
organisation: Hostmaster Ltd
address:      P.O. Box 98
address:      Kyiv  04060
address:      Ukraine
phone:        +1 415 672 3654
fax-no:       +1 978 359 5830
e-mail:       sia@nest.org

nserver:      CD1.NS.UA 194.0.1.9 2001:678:4:0:0:0:0:9
nserver:      HE1.NS.UA 2001:470:2e:1:0:0:0:27 216.218.215.27
nserver:      HO1.NS.UA 195.47.253.1 2001:67c:258:0:0:0:0:1
nserver:      PCH.NS.UA 2001:500:14:6012:ad:0:0:1 204.61.216.12
nserver:      SNS-PB.ISC.ORG 192.5.4.1 2001:500:2e:0:0:0:0:1
ds-rdata:     56514 10 2 bdd7a310534f76b2b6b25c94f816f9b9f260a2e35f526a9287e3307fb2cd16d8

whois:        whois.ua

status:       ACTIVE
remarks:      Registration information: http://hostmaster.ua/

created:      1992-12-01
changed:      2017-03-07
source:       IANA

% Request from 2804:14c:f281:1a64:9c8b:1f18:697c:82c6
% This is the Ukrainian Whois query server #B.
% The Whois is subject to Terms of use
% See https://hostmaster.ua/services/
%
% IN THE PROCESS OF DELEGATION OF A DOMAIN NAME,
% THE REGISTRANT IS AN ENTITY WHO USES AND MANAGES A CERTAIN DOMAIN NAME,
% AND THE REGISTRAR IS A BUSINESS ENTITY THAT PROVIDES THE REGISTRANT
% WITH THE SERVICES NECESSARY FOR THE TECHNICAL MAINTENANCE OF THE REGISTRATION AND OPERATION OF THE DOMAIN NAME.
% FOR INFORMATION ABOUT THE REGISTRANT OF THE DOMAIN NAME, YOU SHOULD CONTACT THE REGISTRAR.

domain:           nic.ua
dom-public:       NO
license:          82263
mnt-by:           ua.nic
nserver:          ns2.uadns.com
nserver:          ns1.uadns.com
status:           clientDeleteProhibited
status:           clientTransferProhibited
created:          2007-10-04 13:40:19+03
modified:         2018-04-19 08:48:24+03
expires:          2020-10-04 13:40:18+03
source:           UAEPP

% Registrar:
% ==========
registrar:        ua.nic
organization:     NIC.UA LLC
organization-loc: ТОВ "НІК.ЮЕЙ"
url:              http://nic.ua
city:             Dnipro
country:          UA
abuse-email:      abuse@nic.ua
abuse-phone:      +380445933222
abuse-postal:     Ukraine 49000 Dnipro PO/BOX 80
abuse-postal-loc: Україна 49000 Дніпро а/с 80
source:           UAEPP


% Query time:     20 msec
